module:
  name: denomination
dataset:
  root: data/raw/denomination/Bangladeshi_Paper_Currency_Raw
  image_size: 224
  num_classes: 9
  class_names:
    - 2
    - 5
    - 10
    - 20
    - 50
    - 100
    - 500
    - 1000
preprocessing:
  aligned_output:
    width: 224
    height: 224