module:
  name: denomination
dataset:
  root: data/raw/denomination/archive/dataset
  image_size: 256
  num_classes: 8
  class_names:
    - 2
    - 5
    - 10
    - 20
    - 50
    - 100
    - 500
    - 1000
preprocessing:
  aligned_output:
    width: 256
    height: 117