seed: 42

experiment:
  name: default

device: auto

dataset:
  image_size: 224
  num_workers: 4
  pin_memory: true
  batch_size: 32
  persistent_workers: true

logging:
  level: INFO

output:
  save_dir: experiments

preprocessing:
  resize_max_dim: 1500

  gaussian_kernel: [5, 5]
  gaussian_sigma: 0

  debug: false
  debug_output_dir: data/processed

  canny:
    adaptive: true
    lower: 50
    upper: 150

  contour:
    min_area_ratio: 0.10
    approx_epsilon: 0.02